export const BALLOON_COLORS = [
  { name: "Gold", hex: "#FFD700", label: "Gold" },
  { name: "Rose Gold", hex: "#E0BFB8", label: "Rose Gold" },
  { name: "Silver", hex: "#C0C0C0", label: "Silver" },
  { name: "Pink", hex: "#FFC0CB", label: "Pink" },
  { name: "Hot Pink", hex: "#FF69B4", label: "Hot Pink" },
  { name: "Blush", hex: "#FFB6C1", label: "Blush" },
  { name: "Blue", hex: "#4169E1", label: "Blue" },
  { name: "Light Blue", hex: "#87CEEB", label: "Light Blue" },
  { name: "Navy", hex: "#000080", label: "Navy" },
  { name: "Red", hex: "#DC143C", label: "Red" },
  { name: "White", hex: "#FFFFFF", label: "White" },
  { name: "Black", hex: "#000000", label: "Black" },
  { name: "Purple", hex: "#9370DB", label: "Purple" },
  { name: "Lavender", hex: "#E6E6FA", label: "Lavender" },
  { name: "Green", hex: "#32CD32", label: "Green" },
  { name: "Mint", hex: "#98FF98", label: "Mint" },
  { name: "Yellow", hex: "#FFD93D", label: "Yellow" },
  { name: "Orange", hex: "#FFA500", label: "Orange" },
  { name: "Peach", hex: "#FFE5B4", label: "Peach" },
  { name: "Coral", hex: "#FF7F50", label: "Coral" },
  { name: "Teal", hex: "#008080", label: "Teal" },
  { name: "Turquoise", hex: "#40E0D0", label: "Turquoise" },
  { name: "Champagne", hex: "#F7E7CE", label: "Champagne" },
  { name: "Burgundy", hex: "#800020", label: "Burgundy" },
  { name: "Emerald", hex: "#50C878", label: "Emerald" },
] as const;

export type BalloonColor = (typeof BALLOON_COLORS)[number]["name"];
